apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app

spec:
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: result-app-pod
    app: demp-voting-app